### ISSUE TITLE
Open bookmark in current tab

### ISSUE THREAD

**Issue by Valtarr** [lucaseverett/toolbar-dial-firefox#6]
Would be nice to open bookmark in current tab. Maybe as an option.  
There is no need to leave speed-dial tab after opening some page. You can just create tab and speed-dial will be there.

**Comment by lucaseverett** [comment]
Hi @Valtarr. Thank you for the comment.

Yes, I will consider that for a future update.

I set it to open in a new tab when clicking a bookmark in a folder because when clicking the back button after visiting the bookmark it would take you back to the main list rather than the folder you were in. To me that seemed like it would be a frustrating experience for users. Also, that's the way Opera works when browsing bookmarks -- it opens the bookmark in a new tab.

**Comment by lucaseverett** [comment]
Hi @Valtarr. This option has been added in version 1.0.11.

**Comment by Valtarr** [comment]
Hi, Lucas.
I'm glad to hear this.
But will be able to try it in 2 weeks.
Unless you make it available for Firefox for Android :)
Thank you for update 👍

нд, 30 черв. 2019, 21:33 користувач Lucas Everett <notifications@github.com>
пише:
